--liquibase formatted sql

--changeset grrado:service-history-service-001 splitStatements:true endDelimiter:; stripComments:false
CREATE TABLE "ServiceHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleId" integer NOT NULL,
    "GarageId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "ServiceDate" timestamp with time zone NOT NULL,
    "MileageKm" double precision NOT NULL,
    "CostAed" numeric NOT NULL,
    "Outcome" text NOT NULL,
    "Notes" text NOT NULL,
    "TechnicianId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ServiceHistories" PRIMARY KEY ("Id")
);
