--liquibase formatted sql

--changeset grrado:vehicle-service-001 splitStatements:true endDelimiter:; stripComments:false
CREATE TABLE "Vehicles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Brand" text NOT NULL,
    "Model" text NOT NULL,
    "Year" integer NOT NULL,
    "VehicleType" text NOT NULL,
    "FuelType" text NOT NULL,
    "Color" text NOT NULL,
    "MileageKm" double precision NOT NULL,
    "LicensePlate" text NOT NULL,
    "City" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id")
);
