--liquibase formatted sql

--changeset grrado:user-service-001 splitStatements:true endDelimiter:; stripComments:false
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "City" text NOT NULL,
    "FamilyType" text NOT NULL,
    "ExperienceLevel" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
