--liquibase formatted sql

--changeset grrado:chatbot-service-001 splitStatements:true endDelimiter:; stripComments:false
CREATE TABLE "AiUsageLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "ServiceName" text NOT NULL,
    "ApiEndpoint" text NOT NULL,
    "OperationType" text NOT NULL,
    "InputTokens" integer NOT NULL,
    "OutputTokens" integer NOT NULL,
    "TotalTokens" integer NOT NULL,
    "Model" text,
    "CostUsd" numeric NOT NULL,
    "DurationMs" integer NOT NULL,
    "IsSuccessful" boolean NOT NULL,
    "ErrorMessage" text,
    "ErrorCode" text,
    "RemainingQuotaPercentage" integer,
    "QuotaResetAt" timestamp with time zone,
    "ConversationId" text,
    "MessageId" text,
    "Tags" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_AiUsageLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "ChatbotConversations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Summary" text,
    "StartedAt" timestamp with time zone NOT NULL,
    "EndedAt" timestamp with time zone,
    "MessageCount" integer NOT NULL,
    "TotalTokensUsed" numeric NOT NULL,
    "TotalCostUsd" numeric NOT NULL,
    "SatisfactionRating" integer,
    "SatisfactionComment" text,
    "ConversationMode" text NOT NULL,
    "IsArchived" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ChatbotConversations" PRIMARY KEY ("Id")
);


CREATE TABLE "ChatbotKnowledgeBases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" text NOT NULL,
    "Question" text NOT NULL,
    "Answer" text NOT NULL,
    "Tags" text,
    "UsageCount" integer NOT NULL,
    "EffectivenessScore" numeric NOT NULL,
    "EmbeddingVector" text,
    "Synonyms" text,
    "RelatedTopics" text,
    "Priority" integer NOT NULL,
    "IsTrainingData" boolean NOT NULL,
    "ModelVersionUsedFor" integer,
    "Confidence" numeric,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ChatbotKnowledgeBases" PRIMARY KEY ("Id")
);


CREATE TABLE "ChatbotMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ConversationId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "UserMessage" text NOT NULL,
    "BotResponse" text NOT NULL,
    "MessageType" text NOT NULL,
    "TokensUsed" integer NOT NULL,
    "CostUsd" numeric NOT NULL,
    "DetectedIntent" text,
    "ConfidenceScore" numeric,
    "ExtractionEntities" text,
    "ResponseTimeMs" integer,
    "IsThinkingMode" boolean NOT NULL,
    "ThinkingProcess" text,
    "IsHelpful" boolean,
    "UserFeedback" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ChatbotMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatbotMessages_ChatbotConversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "ChatbotConversations" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AiImageAnalyses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChatbotMessageId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "OriginalImageFileName" text NOT NULL,
    "OriginalImagePath" text NOT NULL,
    "AnnotatedImagePath" text,
    "ThumbnailPath" text,
    "FileSizeBytes" bigint NOT NULL,
    "ImageMimeType" text NOT NULL,
    "AnalysisType" text NOT NULL,
    "DetectedObjects" text NOT NULL,
    "SeverityLevel" text,
    "DamageType" text,
    "PartsIdentified" text,
    "ConfidenceScore" numeric,
    "Recommendations" text,
    "VehiclePartLocation" text,
    "EstimatedRepairCostRange" integer,
    "RequiresExpertReview" boolean NOT NULL,
    "ResponseTimeMs" integer NOT NULL,
    "TokensUsed" integer NOT NULL,
    "CostUsd" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_AiImageAnalyses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AiImageAnalyses_ChatbotMessages_ChatbotMessageId" FOREIGN KEY ("ChatbotMessageId") REFERENCES "ChatbotMessages" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AiImageAnalyses_ChatbotMessageId" ON "AiImageAnalyses" ("ChatbotMessageId");


CREATE INDEX "IX_ChatbotMessages_ConversationId" ON "ChatbotMessages" ("ConversationId");
