--liquibase formatted sql

--changeset grrado:garage-service-001 splitStatements:true endDelimiter:; stripComments:false
CREATE TABLE "Garages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "City" text NOT NULL,
    "Address" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "GarageType" text NOT NULL,
    "EvSupported" boolean NOT NULL,
    "Rating" double precision NOT NULL,
    "OperatingHours" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Garages" PRIMARY KEY ("Id")
);


CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GarageId" integer NOT NULL,
    "ServiceName" text NOT NULL,
    "Category" text NOT NULL,
    "AvgCostAed" numeric NOT NULL,
    "SkillLevel" text NOT NULL,
    "Description" text NOT NULL,
    "EstimatedDurationMinutes" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Services_Garages_GarageId" FOREIGN KEY ("GarageId") REFERENCES "Garages" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Services_GarageId" ON "Services" ("GarageId");
