--liquibase formatted sql

--changeset grrado:logging-service-001 splitStatements:true endDelimiter:; stripComments:false
CREATE TABLE "ActivityLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "ActivityType" text NOT NULL,
    "Description" text NOT NULL,
    "ResourceType" text,
    "ResourceId" integer,
    "IpAddress" text,
    "UserAgent" text,
    "Metadata" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityType" text NOT NULL,
    "EntityId" integer NOT NULL,
    "Action" text NOT NULL,
    "OldValues" text,
    "NewValues" text,
    "ChangedFields" text,
    "UserId" integer,
    "PerformedBy" text,
    "IpAddress" text,
    "UserAgent" text,
    "Metadata" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "ErrorLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ErrorCode" text NOT NULL,
    "ErrorMessage" text NOT NULL,
    "StackTrace" text NOT NULL,
    "InnerException" text,
    "Source" text NOT NULL,
    "Severity" text NOT NULL,
    "UserId" integer,
    "RequestId" text,
    "IpAddress" text,
    "UserAgent" text,
    "Metadata" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ErrorLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "ErrorMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" uuid NOT NULL,
    "Message" text NOT NULL,
    "Category" text NOT NULL,
    "UseCase" text,
    "LocaleCode" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ErrorMessages" PRIMARY KEY ("Id")
);


CREATE TABLE "RequestResponseLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequestId" text NOT NULL,
    "HttpMethod" text NOT NULL,
    "Endpoint" text NOT NULL,
    "QueryString" text,
    "RequestBody" text,
    "ResponseStatusCode" integer NOT NULL,
    "ResponseBody" text,
    "ResponseTimeMs" bigint NOT NULL,
    "UserId" integer,
    "IpAddress" text,
    "UserAgent" text,
    "Metadata" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_RequestResponseLogs" PRIMARY KEY ("Id")
);
