--liquibase formatted sql

--changeset grrado:diagnostics-service-001 splitStatements:true endDelimiter:; stripComments:false
CREATE TABLE "DiagnosticRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Conditions" text NOT NULL,
    "LogicType" text NOT NULL,
    "Confidence" double precision NOT NULL,
    "Conclusion" text NOT NULL,
    "Description" text NOT NULL,
    "Priority" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_DiagnosticRules" PRIMARY KEY ("Id")
);


CREATE TABLE "ImageDiagnostics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VisualFeature" text NOT NULL,
    "Confidence" double precision NOT NULL,
    "LikelyIssue" text NOT NULL,
    "Urgency" text NOT NULL,
    "FilePath" text NOT NULL,
    "ImageType" text NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ImageDiagnostics" PRIMARY KEY ("Id")
);


CREATE TABLE "VehicleIssues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Symptom" text NOT NULL,
    "AffectedSystem" text NOT NULL,
    "Severity" text NOT NULL,
    "DrivesSafe" boolean NOT NULL,
    "Description" text NOT NULL,
    "PossibleCauses" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_VehicleIssues" PRIMARY KEY ("Id")
);
